CREATE DATABASE OnlineQuizDB;
GO
USE OnlineQuizDB;
GO

CREATE TABLE Teachers(
TeacherID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(100),
Email NVARCHAR(100),
Password NVARCHAR(100),
Role NVARCHAR(20) DEFAULT 'Teacher',
IsActive BIT DEFAULT 1
);

CREATE TABLE Users(
UserID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(100),
Email NVARCHAR(100),
Password NVARCHAR(100),
Role NVARCHAR(20),
TeacherID INT NULL,
IsActive BIT DEFAULT 1,
FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID)
);

CREATE TABLE Admins(
AdminID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(100),
Email NVARCHAR(100),
Password NVARCHAR(100),
Role NVARCHAR(20) DEFAULT 'Admin'
);

CREATE TABLE Questions(
QuestionID INT IDENTITY PRIMARY KEY,
QuestionText NVARCHAR(MAX),
OptionA NVARCHAR(200),
OptionB NVARCHAR(200),
OptionC NVARCHAR(200),
OptionD NVARCHAR(200),
CorrectOption CHAR(1),
DifficultyLevel INT,
TeacherID INT,
SectionID INT NULL,
FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID),
FOREIGN KEY(SectionID) REFERENCES Sections(SectionID)
);

CREATE TABLE Sections(
SectionID INT IDENTITY PRIMARY KEY,
SectionName NVARCHAR(100),
TeacherID INT NOT NULL,
Description NVARCHAR(MAX),
CreatedDate DATETIME DEFAULT GETDATE(),
FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID)
);

CREATE TABLE UserSections(
UserSectionID INT IDENTITY PRIMARY KEY,
UserID INT NOT NULL,
SectionID INT NOT NULL,
EnrolledDate DATETIME DEFAULT GETDATE(),
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(SectionID) REFERENCES Sections(SectionID),
UNIQUE(UserID, SectionID)
);

CREATE TABLE QuizSessions(
SessionID INT IDENTITY PRIMARY KEY,
UserID INT,
TeacherID INT,
Score INT,
StartTime DATETIME,
EndTime DATETIME,
TotalQuestions INT DEFAULT 0,
IsSubmitted BIT DEFAULT 0,
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID)
);

CREATE TABLE UserTeachers(
UserTeacherID INT IDENTITY PRIMARY KEY,
UserID INT NOT NULL,
TeacherID INT NOT NULL,
EnrolledDate DATETIME DEFAULT GETDATE(),
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID),
UNIQUE(UserID, TeacherID)
);

CREATE TABLE Results(
ResultID INT IDENTITY PRIMARY KEY,
UserID INT,
QuestionID INT,
SelectedAnswer CHAR(1),
IsCorrect BIT,
AnsweredAt DATETIME DEFAULT GETDATE(),
SessionID INT,
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(QuestionID) REFERENCES Questions(QuestionID),
FOREIGN KEY(SessionID) REFERENCES QuizSessions(SessionID)
);

